export const UPDATE_PROJECT_TITLE = 'UPDATE_PROJECT_TITLE';

export const ADD_FILE = 'ADD_FILE';
export const REMOVE_FILE = 'REMOVE_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';
export const MOVE_FILE = 'MOVE_FILE';
export const REJECT_FILE = 'REJECT_FILE';

export const UPDATE_PROJECT_URL = 'UPDATE_PROJECT_URL';
export const PUBLISH_PROJECT_ERROR = 'PUBLISH_PROJECT_ERROR';

export const LOAD_PROJECT = 'LOAD_PROJECT';
export const PROJECT_LOADED = 'PROJECT_LOADED';
export const LOAD_PROJECT_ERROR = 'LOAD_PROJECT_ERROR';